### ISSUE TITLE
Use different default keybindings for moving between footnotes

### ISSUE THREAD

**Issue by bhankas** [lazzalazza/org-footnote-assistant#3]
Stock org mode binds `C-c C-n` and `C-c C-p` for moving between headings, and I imagine quite a few people have burned this in their muscle memory just like me.

Perhaps different keybinds are better than disturbing users' defaults?

**Comment by lazzalazza** [comment]
Thanks for your amazing work!!!
I’m going to accept all the code updates as soon as I get home… 

Could you suggest another comfortable keychord? I just went with that but I wouldn’t have expected such a widespread interest in this little package ;)

Andrea

**Comment by lazzalazza** [comment]
I would change the combination to "C-c f n" and "C-c f p". Maybe not so comfortable though. Let me know your thoughts on this.

**Comment by lazzalazza** [comment]
I've modified the key combination: a good thing would be to make them customizable.
